title: Developer Documentation | ThetaLang
description: Language documentation for developers of the Theta programming language
theme: just-the-docs

url: https://dev.theta-lang.org

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
